### PR TITLE
update futures dep to 0.3

### PR DESCRIPTION
**Pull request by serzhiio**

### CODE REVIEW

**Comment by dignifiedquire** [comment]
- needs updated async-std
- needs updating the rust stable version

**Comment by skade** [comment]
I'm tracking and will do the update later.

**Comment by skade** [comment]
Fixed the tests in https://github.com/async-rs/async-tls/commit/cd44fd7adfc24632c07a941c2daf4e05dc68be9e, but I'm not fully happy, especially here:

https://github.com/async-rs/async-tls/blob/master/tests/test.rs#L40-L46

**Comment by dignifiedquire** [comment]
Yeah that is not very nice, but given the current construction we can't implement `AsyncRead` for `&TlsStream` :/ 

Maybe @stjepang has an idea on how we could improve on this?

**Pull request merged**
