### PR TITLE
Add cargo fmt to travis build config

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
@Atul9 Thanks for this PR! It seems this breaks CI on `cargo fmt` -- could you also run `cargo fmt` over the codebase so that CI is green? Thanks!

**Comment by Atul9** [comment]
Hi @yoshuawuyts should I open a new PR for the code changes from running `cargo fmt`? OR include those changes in this PR?

**Comment by yoshuawuyts** [comment]
@Atul9 feel  free to include those here!

**Comment by Atul9** [comment]
@yoshuawuyts done, I have updated the PR & the build has passed.

**Pull request merged**
