### PR TITLE
Bump to rusttls 0.18.0

### PR DESCRIPTION
**Pull request by silverjam**

### CODE REVIEW

**Comment by silverjam** [comment]
cc @skade @dignifiedquire -- anything additional that should be done to test this?

**Comment by yoshuawuyts** [comment]
@dignifiedquire I don't have publish access on Crates.io -- could you run one? Thanks!

**Comment by skade** [comment]
@yoshuawuyts you got an invite.

**Comment by yoshuawuyts** [comment]
@skade thanks; published!

**Pull request merged**
